version: '3'
services:
  ruby:
    container_name: 'sample-ruby'
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      API_KEY: ${API_KEY}
      API_SECRET: ${API_SECRET}
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
    working_dir: '/root/'
    tty: true
    volumes:
      - ./opt:/root/opt